name: CI Pipeline

# Quando o pipeline deve ser executado
on:
  push:
    branches:
      - main
      - developer
  pull_request:
    branches:
      - main
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Verifica o código do repositório
    - name: Checkout the code
      uses: actions/checkout@v3

    # Configura o ambiente Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.16

    # Instala as dependências do Go
    - name: Install dependencies
      run: go mod download

    # Executa os testes
    - name: Run tests
      run: go test ./...

    # Construir a imagem Docker
    - name: Build Docker image
      run: docker build -t thicarvalho/backend_challenge .

    # Logar no Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    # Fazer push da imagem para o Docker Hub
    - name: Push Docker image
      run: docker push thicarvalho/backend_challenge:latest
